// site/src/components/NowPlaying.svelte
<script lang="ts">
	type NowPlaying = {
		state: {
			progress?: number
			duration?: number
			isPlaying: boolean
		}
		track?: {
			name: string
			url: string
			album: string
			artist: string
			coverUrl: string
		} | null
	}

	let nowPlaying: NowPlaying | undefined = undefined
	let fetchTimeout: number

	function fetchNowPlaying() {
		fetch('/api/spotify/now-playing')
			.then((res) => res.json())
			.then((data) => {
				nowPlaying = data
			})
			.catch(() => {
				nowPlaying = { state: { isPlaying: false } }
			})
			.finally(() => {
				clearTimeout(fetchTimeout)
				fetchTimeout = window.setTimeout(fetchNowPlaying, 30 * 1000)
			})
	}

	if (typeof window !== 'undefined') {
		fetchNowPlaying()
		document.addEventListener('visibilitychange', () => {
			document.hidden ? clearTimeout(fetchTimeout) : fetchNowPlaying()
		})
	}
</script>

{#if nowPlaying === undefined}
	<div class="transition-opacity duration-200 opacity-0 h-5 w-5 sm:h-6 sm:w-6" />
{:else if nowPlaying.track}
	<div class="transition-opacity duration-500 opacity-100">
		<a
			href={nowPlaying.track.url}
			class="track-link flex items-center"
			title={`${nowPlaying.track.name} – ${nowPlaying.track.artist}`}
			rel="nofollow"
		>
			<figure
				class="flex-shrink-0 rounded-sm shadow overflow-hidden h-5 w-5 sm:h-6 sm:w-6 mr-2 sm:mr-3 transition-transform duration-300 bg-slate-200 dark:bg-slate-600"
			>
				<img
					src={nowPlaying.track.coverUrl}
					height={64}
					width={64}
					alt={`${nowPlaying.track.name} – ${nowPlaying.track.artist}`}
					loading="lazy"
					decoding="async"
				/>
			</figure>
			<span class="inline-block text-slate-800 dark:text-slate-200 font-medium max-w-xs truncate">
				{nowPlaying.track.name}
			</span>
			<span class="inline-block mx-2">–</span>
			<span class="inline-block text-slate-500 dark:text-slate-300 max-w-max truncate">
				{nowPlaying.track.artist}
			</span>
		</a>
	</div>
{:else}
	<div class="transition-opacity duration-200 flex items-center opacity-60">
		<svg class="opacity-90 flex-shrink-0 h-5 w-5 sm:h-6 sm:w-6 mr-2 sm:mr-3" viewBox="0 0 168 168">
			<path
				fill="#1ED760"
				d="M83.996.277C37.747.277.253 37.77.253 84.019c0 46.251 37.494 83.741 83.743 83.741 46.254 0 83.744-37.49 83.744-83.741 0-46.246-37.49-83.738-83.745-83.738l.001-.004zm38.404 120.78a5.217 5.217 0 01-7.18 1.73c-19.662-12.01-44.414-14.73-73.564-8.07a5.222 5.222 0 01-6.249-3.93 5.213 5.213 0 013.926-6.25c31.9-7.291 59.263-4.15 81.337 9.34 2.46 1.51 3.24 4.72 1.73 7.18zm10.25-22.805c-1.89 3.075-5.91 4.045-8.98 2.155-22.51-13.839-56.823-17.846-83.448-9.764-3.453 1.043-7.1-.903-8.148-4.35a6.538 6.538 0 014.354-8.143c30.413-9.228 68.222-4.758 94.072 11.127 3.07 1.89 4.04 5.91 2.15 8.976v-.001zm.88-23.744c-26.99-16.031-71.52-17.505-97.289-9.684-4.138 1.255-8.514-1.081-9.768-5.219a7.835 7.835 0 015.221-9.771c29.581-8.98 78.756-7.245 109.83 11.202a7.823 7.823 0 012.74 10.733c-2.2 3.722-7.02 4.949-10.73 2.739z"
			/>
		</svg>
		<span class="text-slate-700 dark:text-slate-500">Not Playing</span>
	</div>
{/if}

// src/components/NowPlaying.tsx
import { h } from 'preact'
import { useState, useEffect } from 'preact/hooks'

type Track = Record<string, string>

export function NowPlaying() {
	const [data, setData] = useState<undefined | null | Track>(undefined)

	useEffect(() => {
		fetch('/api/spotify/now-playing')
			.then((r) => r.json())
			.then(() => {
				setData(null)
			})
	}, [])

	if (data === undefined) {
		return <div className="transition-opacity duration-200 opacity-0 h-5 w-5 sm:h-6 sm:w-6" />
	}

	if (data === null) {
		return (
			<div className="transition-opacity duration-200 flex items-center opacity-60">
				<svg
					className="opacity-90 flex-shrink-0 h-5 w-5 sm:h-6 sm:w-6 mr-2 sm:mr-3"
					viewBox="0 0 168 168"
				>
					<path
						fill="#1ED760"
						d="M83.996.277C37.747.277.253 37.77.253 84.019c0 46.251 37.494 83.741 83.743 83.741 46.254 0 83.744-37.49 83.744-83.741 0-46.246-37.49-83.738-83.745-83.738l.001-.004zm38.404 120.78a5.217 5.217 0 01-7.18 1.73c-19.662-12.01-44.414-14.73-73.564-8.07a5.222 5.222 0 01-6.249-3.93 5.213 5.213 0 013.926-6.25c31.9-7.291 59.263-4.15 81.337 9.34 2.46 1.51 3.24 4.72 1.73 7.18zm10.25-22.805c-1.89 3.075-5.91 4.045-8.98 2.155-22.51-13.839-56.823-17.846-83.448-9.764-3.453 1.043-7.1-.903-8.148-4.35a6.538 6.538 0 014.354-8.143c30.413-9.228 68.222-4.758 94.072 11.127 3.07 1.89 4.04 5.91 2.15 8.976v-.001zm.88-23.744c-26.99-16.031-71.52-17.505-97.289-9.684-4.138 1.255-8.514-1.081-9.768-5.219a7.835 7.835 0 015.221-9.771c29.581-8.98 78.756-7.245 109.83 11.202a7.823 7.823 0 012.74 10.733c-2.2 3.722-7.02 4.949-10.73 2.739z"
					/>
				</svg>
				<span className="text-gray-700 dark:text-gray-500">Not Playing</span>
			</div>
		)
	}

	return (
		<div className="transition-opacity duration-500 opacity-100">
			<a
				href={data.url}
				className="track-link flex items-center"
				title={`${data.name} – ${data.artist}`}
				rel="nofollow"
			>
				<figure className="flex-shrink-0 rounded-sm shadow overflow-hidden h-5 w-5 sm:h-6 sm:w-6 mr-2 sm:mr-3 transition-transform duration-300 bg-gray-200 dark:bg-gray-600">
					<img
						key={data.coverUrl}
						src={data.coverUrl}
						height={64}
						width={64}
						alt={`${data.name} – ${data.artist}`}
					/>
				</figure>
				<span className="inline-block text-gray-800 dark:text-gray-200 font-medium max-w-xs truncate">
					{data.name}
				</span>
				<span className="inline-block mx-2">–</span>
				<span className="inline-block text-gray-500 dark:text-gray-300 max-w-max truncate">
					{data.artist}
				</span>
			</a>
		</div>
	)
}
